#!/usr/bin/env node
/* Sunny blog builder.
   Reads Markdown posts from blog/posts/*.md and generates:
     - blog/index.html            (listing page: featured story + grid + city filter)
     - blog/<slug>/index.html     (one page per post)
   When NOINDEX is false it also refreshes the /blog/ entries in sitemap.xml.

   Zero dependencies — run with:  node scripts/build-blog.js
   See blog/posts/README.md for the authoring format. */

'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const POSTS_DIR = path.join(ROOT, 'blog', 'posts');
const BLOG_DIR = path.join(ROOT, 'blog');
const SITE = 'https://sunnypubs.app';
const GENERATED_MARK = '<!-- generated by scripts/build-blog.js — edit blog/posts/*.md instead -->';

// The blog is not public yet. Flip to false at launch: pages stop carrying
// <meta name="robots" content="noindex"> and blog URLs are added to sitemap.xml.
const NOINDEX = true;

// Preferred city order for the filter pills; cities found in posts but not
// listed here are appended alphabetically, so new cities Just Work.
const CITY_ORDER = ['Dublin', 'Cork', 'London', 'Birmingham', 'Manchester'];

const render = require(path.join(BLOG_DIR, 'blog-render.js'));
const esc = render.esc;

/* ── Front matter ─────────────────────────────────────────────── */

function parseFrontMatter(raw, file) {
  const m = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?/);
  if (!m) throw new Error(`${file}: missing front matter (--- block at top)`);
  const meta = {};
  for (const line of m[1].split(/\r?\n/)) {
    if (!line.trim() || line.trim().startsWith('#')) continue;
    const kv = line.match(/^([A-Za-z_][\w-]*):\s*(.*)$/);
    if (!kv) throw new Error(`${file}: bad front matter line: "${line}"`);
    let v = kv[2].trim().replace(/^["'](.*)["']$/, '$1');
    meta[kv[1]] = v;
  }
  return { meta, body: raw.slice(m[0].length) };
}

/* ── Markdown (subset) → post body blocks ─────────────────────────
   Supported:  ## subhead · > pull quote · - bullet list ·
               :::tip … ::: Sunny tip box · paragraphs ·
               **bold** *italic* [link](url)
   The first paragraph becomes the lead. */

function inline(s) {
  return esc(s)
    .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
    .replace(/\*([^*]+)\*/g, '<em>$1</em>')
    .replace(/\[([^\]]+)\]\(([^)\s]+)\)/g, '<a href="$2">$1</a>');
}

function markdownToBlocks(md, file) {
  const blocks = [];
  const lines = md.split(/\r?\n/);
  let i = 0, sawLead = false;
  while (i < lines.length) {
    const line = lines[i];
    if (!line.trim()) { i++; continue; }

    if (line.startsWith(':::tip')) {
      const buf = [];
      i++;
      while (i < lines.length && !lines[i].startsWith(':::')) { buf.push(lines[i]); i++; }
      if (i >= lines.length) throw new Error(`${file}: unclosed :::tip block`);
      i++; // closing :::
      blocks.push({ k: 'tip', t: buf.join(' ').trim() });
      continue;
    }
    if (line.startsWith('## ')) {
      blocks.push({ k: 'h', t: line.slice(3).trim() });
      i++; continue;
    }
    if (line.startsWith('> ')) {
      const buf = [];
      while (i < lines.length && lines[i].startsWith('> ')) { buf.push(lines[i].slice(2)); i++; }
      blocks.push({ k: 'quote', t: buf.join(' ').trim() });
      continue;
    }
    if (/^[-*] /.test(line)) {
      const items = [];
      while (i < lines.length && /^[-*] /.test(lines[i])) { items.push(lines[i].slice(2).trim()); i++; }
      blocks.push({ k: 'list', items });
      continue;
    }
    // paragraph: consume until blank line
    const buf = [];
    while (i < lines.length && lines[i].trim() && !/^(## |> |[-*] |:::)/.test(lines[i])) {
      buf.push(lines[i].trim()); i++;
    }
    blocks.push({ k: sawLead ? 'p' : 'lead', t: buf.join(' ') });
    sawLead = true;
  }
  return blocks;
}

function blocksHtml(blocks) {
  return blocks.map((b) => {
    if (b.k === 'lead') return `<p class="post-lead">${inline(b.t)}</p>`;
    if (b.k === 'p') return `<p class="post-p">${inline(b.t)}</p>`;
    if (b.k === 'h') return `<h2 class="post-h">${inline(b.t)}</h2>`;
    if (b.k === 'quote') return `<blockquote class="post-quote"><p>${inline(b.t)}</p></blockquote>`;
    if (b.k === 'list') {
      return `<ul class="post-list">${b.items.map((it) => `<li><span class="dot" aria-hidden="true"></span><span>${inline(it)}</span></li>`).join('')}</ul>`;
    }
    if (b.k === 'tip') {
      return `<div class="post-tip"><img src="/assets/sunny_icon.png" alt="" aria-hidden="true"><div><div class="post-tip-label">Sunny tip</div><p>${inline(b.t)}</p></div></div>`;
    }
    return '';
  }).join('\n');
}

function wordCount(blocks) {
  let n = 0;
  for (const b of blocks) {
    if (b.t) n += b.t.split(/\s+/).length;
    if (b.items) for (const it of b.items) n += it.split(/\s+/).length;
  }
  return n;
}

/* ── Load posts ───────────────────────────────────────────────── */

const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

function displayDate(iso, file) {
  const m = iso.match(/^(\d{4})-(\d{2})-(\d{2})$/);
  if (!m) throw new Error(`${file}: date must be YYYY-MM-DD (got "${iso}")`);
  return `${Number(m[3])} ${MONTHS[Number(m[2]) - 1]} ${m[1]}`;
}

function loadPosts() {
  if (!fs.existsSync(POSTS_DIR)) throw new Error('blog/posts/ not found');
  const posts = [];
  for (const f of fs.readdirSync(POSTS_DIR).sort()) {
    if (!f.endsWith('.md') || f.toLowerCase() === 'readme.md') continue;
    const file = `blog/posts/${f}`;
    const raw = fs.readFileSync(path.join(POSTS_DIR, f), 'utf8');
    const { meta, body } = parseFrontMatter(raw, file);
    if (meta.draft === 'true') continue;

    for (const req of ['title', 'excerpt', 'category', 'city', 'author', 'date']) {
      if (!meta[req]) throw new Error(`${file}: front matter is missing "${req}"`);
    }
    if (!render.CATEGORY[meta.category]) {
      throw new Error(`${file}: category must be one of ${Object.keys(render.CATEGORY).join(' | ')}`);
    }

    const slug = (meta.slug || f.replace(/\.md$/, '')).toLowerCase()
      .replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
    const blocks = markdownToBlocks(body, file);
    const image = meta.image
      ? { type: 'photo', src: meta.image }
      : { type: 'grad', grad: meta.gradient || 'sunset' };

    posts.push({
      slug,
      title: meta.title,
      excerpt: meta.excerpt,
      category: meta.category,
      city: meta.city,
      author: meta.author,
      isoDate: meta.date,
      date: displayDate(meta.date, file),
      read: meta.read || `${Math.max(2, Math.round(wordCount(blocks) / 200))} min`,
      featured: meta.featured === 'true',
      image,
      blocks
    });
  }
  posts.sort((a, b) => (a.isoDate < b.isoDate ? 1 : a.isoDate > b.isoDate ? -1 : 0));
  const seen = new Set();
  for (const p of posts) {
    if (seen.has(p.slug)) throw new Error(`duplicate slug "${p.slug}"`);
    seen.add(p.slug);
  }
  return posts;
}

function cityList(posts) {
  const found = new Set(posts.map((p) => p.city));
  const ordered = CITY_ORDER.filter((c) => found.has(c));
  const extra = [...found].filter((c) => !CITY_ORDER.includes(c)).sort();
  return ordered.concat(extra);
}

/* ── Page chrome (matches the rest of the marketing site) ─────── */

function head({ title, description, canonical, ogImage }) {
  return `<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
  <title>${esc(title)}</title>
  <meta name="description" content="${esc(description)}">${NOINDEX ? '\n  <meta name="robots" content="noindex">' : ''}
  <link rel="icon" href="/assets/sunny_icon.png">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Fraunces:ital,wght@0,500;0,600;0,700;1,600&family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
  <link rel="canonical" href="${canonical}">
  <meta property="og:title" content="${esc(title)}">
  <meta property="og:description" content="${esc(description)}">
  <meta property="og:type" content="${canonical.endsWith('/blog/') ? 'website' : 'article'}">
  <meta property="og:url" content="${canonical}">
  <meta property="og:image" content="${ogImage}">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="${esc(title)}">
  <meta name="twitter:description" content="${esc(description)}">
  <meta name="twitter:image" content="${ogImage}">
  <script src="/js/consent.js"></script>
  <script>window.SunnyConsent?.initConsent();</script>
  <link rel="stylesheet" href="/style.css">
  <link rel="stylesheet" href="/blog/blog.css">`;
}

const HEADER = `<header class="header is-scrolled">
    <div class="container header-inner">
      <a href="/" class="brand" aria-label="Sunny home">
        <img src="/assets/sunny_icon.png" alt="Sunny" class="brand-mark">
        <span class="brand-name">Sunny</span>
      </a>
      <nav class="nav">
        <a href="https://visit.sunnypubs.app">Web App</a>
        <a href="/blog/" class="is-current">Blog</a>
        <a href="/contact-us/">Contact</a>
        <a href="/privacy-policy/">Privacy</a>
      </nav>
      <div class="header-cta">
        <a href="https://visit.sunnypubs.app" class="btn btn-primary">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22s7-7.58 7-13a7 7 0 1 0-14 0c0 5.42 7 13 7 13Z"/><circle cx="12" cy="9" r="2.5"/></svg>
          View Sunny Map
        </a>
        <button class="mobile-menu-btn" aria-label="Menu" onclick="document.querySelector('.nav').classList.toggle('is-open')">
          <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><line x1="3" y1="6" x2="21" y2="6"/><line x1="3" y1="12" x2="21" y2="12"/><line x1="3" y1="18" x2="21" y2="18"/></svg>
        </button>
      </div>
    </div>
  </header>`;

const NEWSLETTER = `<div class="newsletter-cta">
        <img class="newsletter-motif" src="/assets/sunny_sun_motif.png" alt="" aria-hidden="true">
        <div class="newsletter-text">
          <h3>Get the sun, in your inbox.</h3>
          <p>New city guides and venue spotlights, every Friday. No noise, just where to catch the next good afternoon.</p>
        </div>
        <form class="newsletter-form" data-newsletter>
          <input type="email" name="email" placeholder="you@email.com" required aria-label="Email address">
          <button type="submit" class="btn btn-primary">Sign up</button>
        </form>
      </div>`;

const FOOTER = `<footer class="footer">
    <div class="container">
      <div class="footer-grid">
        <div class="footer-brand">
          <div class="brand">
            <img src="/assets/sunny_icon.png" alt="Sunny" class="brand-mark">
            <span class="brand-name">Sunny</span>
          </div>
          <p>Find pubs and beer gardens in the sun, right now.</p>
        </div>
        <div class="footer-col">
          <h4>Company</h4>
          <ul>
            <li><a href="/blog/">Blog</a></li>
            <li><a href="/contact-us/">Contact</a></li>
          </ul>
        </div>
        <div class="footer-col">
          <h4>Legal</h4>
          <ul>
            <li><a href="/privacy-policy/">Privacy</a></li>
            <li><a href="/terms-and-conditions/">Terms &amp; conditions</a></li>
            <li><a href="#" data-cookie-settings>Cookie settings</a></li>
          </ul>
        </div>
      </div>
      <div class="footer-base">
        <span>&copy; 2026 Sunny Apps Ltd. All rights reserved.</span>
        <span>sunnypubs.app</span>
      </div>
    </div>
  </footer>`;

// Listing metadata embedded for the client-side city filter (no bodies).
function postsJson(posts) {
  return JSON.stringify(posts.map((p) => ({
    slug: p.slug, title: p.title, excerpt: p.excerpt, category: p.category,
    city: p.city, author: p.author, date: p.date, read: p.read,
    featured: p.featured, image: p.image
  }))).replace(/</g, '\\u003c');
}

/* ── Listing page ─────────────────────────────────────────────── */

function listingPage(posts, cities) {
  const counts = { __all: posts.length };
  for (const c of cities) counts[c] = posts.filter((p) => p.city === c).length;
  const state = render.listingState(posts, 'All');

  return `<!DOCTYPE html>
<html lang="en">
${GENERATED_MARK}
<head>
  ${head({
    title: 'Blog — Sunny',
    description: 'Venue spotlights, city guides and the latest from Sunny — all about finding the next good afternoon outdoors.',
    canonical: `${SITE}/blog/`,
    ogImage: `${SITE}/assets/hero_garden.png`
  })}
</head>
<body>

  ${HEADER}

  <main class="blog-page">
    <section class="blog-wrap blog-masthead">
      <div class="eyebrow">The Sunny blog</div>
      <h1 class="blog-title">Stories from the<br>sunny side of the city.</h1>
      <p class="blog-sub">Venue spotlights, city guides and the latest from Sunny — all about finding the next good afternoon outdoors.</p>
      <div class="city-filter" id="cityFilter">${render.pillsHtml(cities, 'All', counts)}</div>
    </section>

    <section class="blog-wrap" id="featuredSlot">${state.featured ? render.featureHtml(state.featured) : ''}</section>

    <section class="blog-wrap blog-grid-section">
      <div class="blog-grid-head">
        <h2 id="gridHeading">${esc(state.heading)}</h2>
        <span id="gridCount">${esc(state.countText)}</span>
      </div>
      <div class="post-grid" id="postGrid">
        ${state.rest.map((p) => render.cardHtml(p)).join('\n        ')}
      </div>
    </section>

    <section class="blog-wrap newsletter-section">
      ${NEWSLETTER}
    </section>
  </main>

  ${FOOTER}

  <script>window.SUNNY_BLOG = { posts: ${postsJson(posts)}, cities: ${JSON.stringify(cities)} };</script>
  <script src="/blog/blog-render.js"></script>
  <script src="/blog/blog.js"></script>
</body>
</html>
`;
}

/* ── Post page ────────────────────────────────────────────────── */

function postPage(post, posts, cities) {
  const initials = post.author.split(' ').map((w) => w[0]).slice(0, 2).join('');
  const related = render.relatedPosts(posts, post.slug, post.city);
  const ogImage = post.image.type === 'photo'
    ? SITE + post.image.src
    : `${SITE}/assets/hero_garden.png`;

  return `<!DOCTYPE html>
<html lang="en">
${GENERATED_MARK}
<head>
  ${head({
    title: `${post.title} — Sunny Blog`,
    description: post.excerpt,
    canonical: `${SITE}/blog/${post.slug}/`,
    ogImage
  })}
  <script type="application/ld+json">
  ${JSON.stringify({
    '@context': 'https://schema.org',
    '@type': 'BlogPosting',
    headline: post.title,
    description: post.excerpt,
    datePublished: post.isoDate,
    author: { '@type': 'Person', name: post.author },
    publisher: { '@type': 'Organization', name: 'Sunny Apps Ltd', logo: { '@type': 'ImageObject', url: `${SITE}/assets/sunny_icon.png` } },
    image: ogImage,
    mainEntityOfPage: `${SITE}/blog/${post.slug}/`
  }, null, 2).replace(/\n/g, '\n  ')}
  </script>
</head>
<body class="post-page">

  <div class="post-topbar">
    <div class="post-topbar-inner">
      <a class="back-pill" href="/blog/">
        <svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M19 12H5M12 19l-7-7 7-7"/></svg>
        All stories
      </a>
      <a class="brand" href="/" aria-label="Sunny home">
        <img src="/assets/sunny_icon.png" alt="Sunny" class="brand-mark">
        <span class="brand-name">Sunny</span>
      </a>
    </div>
  </div>

  <main>
    <article class="post-article post-header">
      <div class="post-tags">
        ${render.categoryTag(post, false)}
        ${render.cityTag(post.city)}
      </div>
      <h1 class="post-title">${esc(post.title)}</h1>
      <p class="post-standfirst">${esc(post.excerpt)}</p>
      <div class="post-byline">
        <div class="author-avatar" aria-hidden="true">${esc(initials)}</div>
        ${render.metaLine(post)}
      </div>
    </article>

    <div class="post-hero">
      ${render.mediaHtml(post, 'post-hero-media')}
    </div>

    <article class="post-article post-body">
      ${blocksHtml(post.blocks)}
    </article>

    <section class="post-more">
      <div class="post-more-inner">
        <div class="post-more-head">
          <div class="eyebrow">Browse by city</div>
          <h3 id="moreHeading">More stories in ${esc(post.city)}</h3>
        </div>
        <div class="city-filter city-filter-sm" id="cityFilter">${render.pillsHtml(cities, post.city)}</div>
        <div class="related-grid" id="relatedGrid">
          ${related.length
            ? related.map((p) => render.relatedCardHtml(p)).join('\n          ')
            : `<p class="related-empty">No other stories in ${esc(post.city)} yet — more sunny spots coming soon.</p>`}
        </div>
      </div>
    </section>

    <section class="blog-wrap newsletter-section">
      ${NEWSLETTER}
    </section>
  </main>

  ${FOOTER}

  <script>window.SUNNY_BLOG = { posts: ${postsJson(posts)}, cities: ${JSON.stringify(cities)}, currentSlug: ${JSON.stringify(post.slug)}, currentCity: ${JSON.stringify(post.city)} };</script>
  <script src="/blog/blog-render.js"></script>
  <script src="/blog/blog.js"></script>
</body>
</html>
`;
}

/* ── Sitemap (only once the blog is public) ───────────────────── */

function updateSitemap(posts) {
  const file = path.join(ROOT, 'sitemap.xml');
  let xml = fs.readFileSync(file, 'utf8');
  // Drop any existing /blog/ entries, then re-append fresh ones.
  xml = xml.replace(/\s*<url>\s*<loc>https:\/\/sunnypubs\.app\/blog\/[\s\S]*?<\/url>/g, '');
  const entries = [`  <url>
    <loc>${SITE}/blog/</loc>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>`].concat(posts.map((p) => `  <url>
    <loc>${SITE}/blog/${p.slug}/</loc>
    <changefreq>monthly</changefreq>
    <priority>0.5</priority>
  </url>`));
  xml = xml.replace('</urlset>', entries.join('\n') + '\n</urlset>');
  fs.writeFileSync(file, xml);
  console.log('sitemap.xml updated with blog URLs');
}

/* ── Main ─────────────────────────────────────────────────────── */

function main() {
  const posts = loadPosts();
  if (!posts.length) throw new Error('no posts found in blog/posts/');
  const cities = cityList(posts);

  // Remove previously generated post directories whose source .md is gone.
  const slugs = new Set(posts.map((p) => p.slug));
  for (const entry of fs.readdirSync(BLOG_DIR, { withFileTypes: true })) {
    if (!entry.isDirectory() || entry.name === 'posts') continue;
    const idx = path.join(BLOG_DIR, entry.name, 'index.html');
    if (fs.existsSync(idx) && fs.readFileSync(idx, 'utf8').includes(GENERATED_MARK) && !slugs.has(entry.name)) {
      fs.rmSync(path.join(BLOG_DIR, entry.name), { recursive: true });
      console.log(`removed stale blog/${entry.name}/`);
    }
  }

  fs.writeFileSync(path.join(BLOG_DIR, 'index.html'), listingPage(posts, cities));
  console.log('built blog/index.html');

  for (const post of posts) {
    const dir = path.join(BLOG_DIR, post.slug);
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(dir, 'index.html'), postPage(post, posts, cities));
    console.log(`built blog/${post.slug}/index.html`);
  }

  if (!NOINDEX) updateSitemap(posts);
  console.log(`\n${posts.length} posts · cities: ${cities.join(', ')}${NOINDEX ? '\nNOINDEX is on — pages carry a noindex tag and sitemap.xml is untouched.' : ''}`);
}

main();
